spring.application.name=exam-management-system

spring.datasource.url=jdbc:postgresql://localhost:5432/exam_management
spring.datasource.username=rsilinevich
spring.datasource.password=

# Hibernate will automatically create/update tables to match Java classes
spring.jpa.hibernate.ddl-auto=update

# Shows the exact SQL Hibernate generates in IntelliJ console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true